# fly.toml app configuration file generated for fd-s1-wandering-resonance-2779 on 2023-12-04T11:28:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fd-s1"
primary_region = "otp"

[build]

[[mounts]]
  source = "pb_data"
  destination = "/pb/pb_data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
